### ISSUE TITLE
"Page loading" spinner shows constantly

### ISSUE THREAD

**Issue by kadoban** [kgsHtml/kgs-html-issues#5]
When the client is running, the "page loading" spinner never goes away. I believe there's some way to make it disappear, as it's pretty distracting.

On a similar note, it constantly shows that it's reading from ajax.googleapis.com in the status area, which actually covers up the textbox where you write chats.

(Only tested in Firefox, but others probably show something similar).

**Comment by wshubert** [comment]
No more dojoclient.
