### ISSUE TITLE
<gmt> tags aren't working.

### ISSUE THREAD

**Issue by kadoban** [kgsHtml/kgs-html-issues#7]
There's nothing handling <gmt> tags, so they display raw. We need to figure out the right way to handle those, which probably has a lot to do with discovering at which level we can query the local timezone most reliably.

**Comment by wshubert** [comment]
I can easily do the translation on the java side; the code is already there for the android and java clients. I just need to know the time zone for the client. Would it be hard for the client to transmit that as part of the login request?

**Comment by wshubert** [comment]
No more dojoclient! Closing out.
