### ISSUE TITLE
Right-click in user list, context menu can't be cancelled

### ISSUE THREAD

**Issue by kadoban** [kgsHtml/kgs-html-issues#9]
When you right-click in the user list, it brings up the "Friend/Fan/Censor" context menu. There is no way to close the menu without toggling one of those, as far as I can tell.

In a similar vein, it may be nice to have menus of all kind close themselves when you click on another part of the UI, as is usually done in interfaces like this.

**Comment by wshubert** [comment]
No more dojoclient! Closing out.
